baseURL = "https://recipe.puvvadi.me"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "KD's Food Dairy"
theme = "dream"

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]


    # dark mode
    defaultDark = true
    background = "#fff"
    backgroundImage = "/img/background-dark.jpg"
    darkLinkColor = "darkseagreen"
    #darkNav = true
    dark404 = true

    favicon = "/img/avatar.jpg"


    author = "KD's Food Diary"
    email = "kd@puvvadi.me"
    twitter = "kdsfood_diary"
    facebook = "kdsfood.diary"
    instagram = "kdsfood.diary"
    github = "kdpuvvadi"

    avatar = "/img/avatar.jpg"
    
    siteStartYear = 2019

    enableSearch = true
    rss = true


    showSummaryCoverInPost = true
    


[params.advanced]
    customCSS = ["css/custom.css"]
    customJS = []