baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "KD's Food Dairy"
theme = "dream"

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]


    # dark mode
    defaultDark = true
    backgroundDark = "black"
    backgroundImage = "/img/background.jpg"
    darkLinkColor = "darkseagreen"
    darkNav = true
    dark404 = true



    author = "KD's Food Diary"
    email = "kd@puvvadi.me"
    twitter = "kdsfood.diary"
    facebook = "kdsfood.diary"
    instagram = "kdsfood.diary"
    github = "kdpuvvadi"

    avatar = "/img/avatar.jpg"
    
    siteStartYear = 2019

    enableSearch = true
    rss = true


    showSummaryCoverInPost = true
    


